export enum USER_STATUS {
  CREATED = "CREATED",
  STEP_ONE = "STEP_1",
  STEP_TWO = "STEP_2",
  STEP_THREE = "STEP_3",
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  SUSPENDED = "SUSPENDED",
}

export enum USER_TYPES {
  ADMIN = "ADMINISTRADOR",
  WAITER = "MESERO",
  KITCHEN = "COCINA",
  CAJA = "CAJERO",
}
