import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../ui/styles/globals.css";
import { cookies } from "next/headers";
import { SecurityUseCases } from "@application/Security/SecurityUseCases";
import { AuthWrapper } from "@ui/components/AuthWrapper";
import { Head } from "next/document";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  auth,
  anonym,
}: Readonly<{
  auth: React.ReactNode;
  anonym: React.ReactNode;
}>) {
  const checkUser = async () => {
    try {
      const cookie = await cookies();
      const token = cookie.get("token")?.value;
      if (token) {
        const security = new SecurityUseCases();
        security.decriptJWT(token);
        return true;
      }
      return false;
    } catch (e) {
      return false;
    }
  };
  const isLoggin = await checkUser();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {isLoggin ? <AuthWrapper>{auth}</AuthWrapper> : anonym}
      </body>
    </html>
  );
}
